### ISSUE TITLE
해당 알고리즘 사이트 아이디도 같이 적어주세요

### ISSUE THREAD

**Issue by Bue-von-hon** [sungmen/Solve_Algorithms#1]
지금 풀이 코드만 보이는데 문제지도 같이 볼 수 있게 아이디도 적어주세요

**Comment by sungmen** [comment]
https://www.acmicpc.net/user/jsm2548
https://swexpertacademy.com/main/userpage/home/userHome.do?userId=AXAi1AP6qPgDFAXq
